sudo: required
services:
  - docker

before_install:
  - docker build -t miraclebg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true miraclebg/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-763366179883"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
