sudo: required
services:
  - docker

before_install:
  - docker build -t miraclebg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true miraclebg/docker-react npm run test -- --coverage
